set(GRAVEYARD_CCE_PATH "/opt/cray/pe/cce/18.0.0" CACHE PATH "")
set(GRAVEYARD_ROCM_PATH "/opt/rocm-6.1.2" CACHE PATH "")

set(CMAKE_C_COMPILER "${GRAVEYARD_CCE_PATH}/bin/craycc" CACHE PATH "")
set(CMAKE_CXX_COMPILER "${GRAVEYARD_CCE_PATH}/bin/crayCC" CACHE PATH "")
set(CMAKE_Fortran_COMPILER "${GRAVEYARD_CCE_PATH}/bin/crayftn" CACHE PATH "")

set(CMAKE_HIP_COMPILER "${GRAVEYARD_ROCM_PATH}/bin/amdclang++" CACHE PATH "")
set(CMAKE_HIP_ARCHITECTURES "gfx942" CACHE STRING "")
set(CMAKE_HIP_PLATFORM "amd" CACHE STRING "")
set(AMDGPU_TARGETS "gfx942" CACHE STRING "")
set(GPU_TARGETS "gfx942" CACHE STRING "")

set(GRAVEYARD_FORTRAN_OMPOL_FLAGS "--rocm-path=${GRAVEYARD_ROCM_PATH};-homp;-target-accel=${CMAKE_HIP_PLATFORM}_${CMAKE_HIP_ARCHITECTURES};-haccel=${CMAKE_HIP_PLATFORM}_${CMAKE_HIP_ARCHITECTURES}" CACHE STRING "")
set(GRAVEYARD_OMP_LINK_FLAGS "-fopenmp" CACHE STRING "")

