set(GRAVEYARD_CCE_PATH "/opt/cray/pe/cce/18.0.0" CACHE PATH "")
set(GRAVEYARD_ROCM_PATH "/opt/rocm-6.2.0" CACHE PATH "")

set(CMAKE_C_COMPILER "${GRAVEYARD_CCE_PATH}/bin/craycc" CACHE PATH "")
set(CMAKE_CXX_COMPILER "${GRAVEYARD_CCE_PATH}/bin/crayCC" CACHE PATH "")
set(CMAKE_Fortran_COMPILER "${GRAVEYARD_CCE_PATH}/bin/crayftn" CACHE PATH "")

set(CMAKE_HIP_COMPILER "${GRAVEYARD_ROCM_PATH}/bin/amdclang++" CACHE PATH "")
set(CMAKE_HIP_ARCHITECTURES "gfx942" CACHE STRING "")
set(CMAKE_HIP_PLATFORM "amd" CACHE STRING "")
set(AMDGPU_TARGETS "gfx942" CACHE STRING "")
set(GPU_TARGETS "gfx942" CACHE STRING "")

set(GRAVEYARD_FORTRAN_OMPOL_FLAGS "--rocm-path=${GRAVEYARD_ROCM_PATH};-homp;-target-accel=${CMAKE_HIP_PLATFORM}_${CMAKE_HIP_ARCHITECTURES};-haccel=${CMAKE_HIP_PLATFORM}_${CMAKE_HIP_ARCHITECTURES}" CACHE STRING "")
set(GRAVEYARD_OMP_LINK_FLAGS "-fopenmp" CACHE STRING "")

#list(APPEND CMAKE_PREFIX_PATH "${GRAVEYARD_ROCM_PATH}/lib/cmake")
#set(GRAVEYARD_HIP_LINK_FLAGS "-fgpu-rdc --hip-link --rocm-path=${GRAVEYARD_ROCM_PATH} -L${GRAVEYARD_ROCM_PATH}/lib -lamdhip64" CACHE STRING "")

# Maybe we need these?
#set(CMAKE_Fortran_FLAGS "-ffree" CACHE PATH "")

#set(CMAKE_Fortran_FLAGS_RELEASE "-O3 -g -ef" CACHE PATH "")
#set(CMAKE_Fortran_FLAGS_RELWITHDEBINFO "-O3 -g -ef" CACHE PATH "")
#set(CMAKE_Fortran_FLAGS_DEBUG "-O0 -g -ef" CACHE PATH "")

#set(CMAKE_CXX_FLAGS_RELEASE "-O3 -g" CACHE PATH "")
#set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -g" CACHE PATH "")
#set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g" CACHE PATH "")
